services:
  db:
    image: postgres:16
    container_name: aso-postgres
    environment:
      POSTGRES_DB: aso_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: aso-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  email-renderer:
    build:
      context: ./clojure/email-renderer
    container_name: aso-email-renderer
    ports:
      - "3000:3000"

  app:
    build: .
    container_name: aso-service-app
    depends_on:
      - db
      - mailhog
      - email-renderer
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/aso_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM: noreply@aston-martin-aso.local
      EMAIL_RENDERER_URL: http://email-renderer:3000
