-- Baseline schema matching the Hibernate-mapped entities (joined Employee inheritance).

CREATE TABLE customer (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL,
    first_name      VARCHAR(255) NOT NULL,
    last_name       VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255)
);

CREATE TABLE employee (
    employee_type   VARCHAR(31) NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL,
    first_name      VARCHAR(255) NOT NULL,
    last_name       VARCHAR(255) NOT NULL,
    login           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255),
    role            VARCHAR(255),
    CONSTRAINT employee_employee_type_check CHECK (employee_type IN ('ADMIN', 'WORKER')),
    CONSTRAINT employee_role_check CHECK (role IN (
        'ADMIN', 'CEO', 'COO', 'CLIENT_SERVICE_CONSULTANT', 'MECHANIC', 'APPRENTICE_MECHANIC'
    ))
);

CREATE TABLE admin (
    id BIGINT PRIMARY KEY REFERENCES employee (id)
);

CREATE TABLE worker (
    id BIGINT PRIMARY KEY REFERENCES employee (id)
);

CREATE TABLE vehicle (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body_style            VARCHAR(255),
    configuration_id      VARCHAR(255),
    drivetrain            VARCHAR(255),
    engine                VARCHAR(255),
    model                 VARCHAR(255) NOT NULL,
    model_line            VARCHAR(255),
    power                 VARCHAR(255),
    production_era        VARCHAR(255),
    production_year       INTEGER,
    removed_from_account  BOOLEAN NOT NULL DEFAULT FALSE,
    security_code         VARCHAR(255),
    transmission          VARCHAR(255),
    vin                   VARCHAR(255) NOT NULL,
    customer_id           BIGINT REFERENCES customer (id)
);

CREATE TABLE service_booking (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    availability_notes       VARCHAR(500),
    cancellation_reason      VARCHAR(500),
    cancelled_by             VARCHAR(255),
    car_model                VARCHAR(255) NOT NULL,
    customer_description     VARCHAR(2000),
    customer_name            VARCHAR(255) NOT NULL,
    estimated_cost           NUMERIC(38, 2),
    estimated_drop_off_time  TIMESTAMP(6),
    final_cost               NUMERIC(38, 2),
    scheduled_date_time      TIMESTAMP(6),
    status                   SMALLINT,
    assigned_worker_id       BIGINT REFERENCES worker (id),
    vehicle_id               BIGINT REFERENCES vehicle (id),
    CONSTRAINT service_booking_cancelled_by_check CHECK (
        cancelled_by IS NULL OR cancelled_by IN ('CUSTOMER', 'WORKER', 'WORKSHOP')
    ),
    CONSTRAINT service_booking_status_check CHECK (status IS NULL OR (status >= 0 AND status <= 3))
);

CREATE TABLE booking_service_types (
    booking_id    BIGINT NOT NULL REFERENCES service_booking (id),
    service_type  VARCHAR(255)
);
