-- Client email verification flag + one-time tokens for password reset / verify-email.
ALTER TABLE customer
    ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;

-- Existing accounts (seeded tests / prior demos) stay usable without re-verifying.
UPDATE customer SET email_verified = TRUE;

CREATE TABLE customer_account_token (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT NOT NULL REFERENCES customer (id) ON DELETE CASCADE,
    token_hash   VARCHAR(255) NOT NULL,
    purpose      VARCHAR(32) NOT NULL,
    expires_at   TIMESTAMP(6) NOT NULL,
    used_at      TIMESTAMP(6),
    CONSTRAINT customer_account_token_purpose_check CHECK (
        purpose IN ('PASSWORD_RESET', 'EMAIL_VERIFICATION')
    ),
    CONSTRAINT uq_customer_account_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_customer_account_token_customer
    ON customer_account_token (customer_id);
