-- Durable email outbox: domain changes write a PENDING row in the same DB transaction.
-- A worker sends asynchronously and retries after crashes / SMTP failures.
CREATE TABLE email_outbox (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel           VARCHAR(32)  NOT NULL,
    event             VARCHAR(64)  NOT NULL,
    status            VARCHAR(32)  NOT NULL,
    booking_id        BIGINT       REFERENCES service_booking (id),
    customer_id       BIGINT       REFERENCES customer (id),
    previous_status   SMALLINT,
    payload_json      TEXT,
    attempt_count     INTEGER      NOT NULL DEFAULT 0,
    max_attempts      INTEGER      NOT NULL DEFAULT 5,
    last_error        VARCHAR(1000),
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    next_attempt_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at           TIMESTAMP(6),
    CONSTRAINT email_outbox_channel_check CHECK (channel IN ('BOOKING', 'CUSTOMER')),
    CONSTRAINT email_outbox_status_check CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX idx_email_outbox_due
    ON email_outbox (status, next_attempt_at);
